export const EMAIL_CHANGED = 'email_changed'; //export default exports just one
export const PASSWORD_CHANGED = 'password_changed';
export const LOGIN_USER_SUCCESS = 'login_user_success';
export const LOGIN_USER_FAIL = 'login_user_fail';
export const LOGIN_USER = 'login_user';
export const SIGNUP_USER_FAIL = 'signup_user_fail';
export const SIGNUP_USER_SUCCESS = 'signup_user_success';
export const SIGNUP_USER = 'signup_user';
export const ALBUM_ADD = 'album_add';
export const USER_UPDATE = 'user_update';
export const ALBUM_FETCH_SUCCESS = 'album_fetch_success';
export const ACCOUNT_SELECTED = 'account_selected';
export const FETCHING_ALBUMS = 'fetching_albums';
export const GENRE_ALL = 'genre_all';
export const GENRE_CHANGED = 'genre_changed';
